# Generated by Django 5.1 on 2024-09-04 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=30)),
                ('product_description', models.CharField(max_length=50)),
                ('product_price', models.IntegerField()),
                ('product_img', models.ImageField(upload_to='img/')),
            ],
        ),
    ]
