# Generated by Django 5.1 on 2024-09-19 05:23

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_sighn_up'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custumer_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('address', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=20)),
                ('date', models.DateTimeField(verbose_name=datetime.datetime(2024, 9, 19, 10, 53, 5, 805813))),
                ('status', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.sighn_up')),
            ],
        ),
    ]
