# Generated by Django 5.1 on 2024-09-19 07:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_custumer_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custumer_order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 19, 12, 55, 44, 242941)),
        ),
    ]
