# Generated by Django 5.1 on 2024-09-23 06:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_custumer_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custumer_order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 23, 11, 36, 17, 109595)),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=30)),
                ('payment_id', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.sighn_up')),
            ],
        ),
    ]
