# Generated by Django 5.1 on 2024-09-26 08:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_custumer_order_date_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custumer_order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 26, 14, 5, 35, 903659)),
        ),
        migrations.RemoveField(
            model_name='payment',
            name='product',
        ),
        migrations.AddField(
            model_name='payment',
            name='product',
            field=models.ManyToManyField(to='store.product'),
        ),
    ]
